name: 'pr-publishing'
description: 'An action for publishing PRs'

inputs:
  artifacts_base_path:
    required: true
    description: 'Base paths for artifacts'
  self-name:
    description: 'The name of the self-user'
    default: 'github-actions[bot]'

runs:
  using: node20
  main: dist/index.js
